### ISSUE TITLE
Impossible to search for a nickname!

### ISSUE THREAD

**Issue by PikaKhan** [neyl66/aoe2-overlay#1]
![image](https://github.com/neyl66/aoe2-overlay/assets/121667018/ea6a4b0e-dd57-444e-8713-46545dedcd14)
Hi, it seems that it has become impossible to search for a nickname!

**Comment by neyl66** [comment]
Oh i see, thank you for reporting this

**Comment by neyl66** [comment]
Hello, i just pushed a fix, sorry it took this long.

I also added a player's games count to the search result list, to help distinguishing players that have same name and country. I'm open to any feedback to it.
